sudo: false
language: python
python: '3.7'

script:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -u -p $HOME/miniconda
  - export PATH="$HOME/minicoonda/bin:$PATH"
  - hash -r
  - pip install nose coverage coveralls flake8 scikit-image
  - pip install -e .
  - flake8
  - nosetests -sv --with-doctest --no-byte-compile --with-coverage --cover-package=tftb
after_success:
  coveralls
